### ISSUE TITLE
Interest earned never shows anything

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#138]
1. go to https://v2.rari.capital/
2. connect metamask wallet with RSPT in it
3. look at interest earned

Expected: has something there
Actual: "?"
![image](https://user-images.githubusercontent.com/1206775/96828243-7a3af700-1461-11eb-80ff-88f9a0d3cdf4.png)

Investigation: Opening the console and looking at the request its making, 
`https://api.rari.capital/pools/stable/interest/WALLET_ADDRESS?fromBlock=0&toBlock=latest` is returning:

`Error: Returned error: daily request count exceeded, request rate limited`

**Comment by jameselkins** [comment]
@TransmissionsDev has my wallet address if you'd like to test that specifically, but it should fail for any address

**Comment by tongnk** [comment]
+1 happening to me too

**Comment by TransmissionsDev** [comment]
Yeah this is because our Infura URL is being ratelimited on our API 

Will be fixed when our other engineer gets on today.

**Comment by jameselkins-mantl** [comment]
This ticket should not be closed because it is not fixed.
