### ISSUE TITLE
withdrawing money from stable pool creates javascript alert

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#140]
Description:
1. go to https://v2.rari.capital
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool
4. click on gear in upper-right hand corner of modal
5. click on 'want to withdraw'
6. choose USDC
7. type "10"
8. click "confirm"

Expected:
metamask pops up asking you to first approve then "unstake" the required amount of RSPT to get 10USDC

Actual:
get a javascript alert asking you "You will withdraw $10.03992. Do  you approve?"

![image](https://user-images.githubusercontent.com/1206775/96828871-9ab78100-1462-11eb-8d12-404feb307293.png)

This is confusing because I am confronted with an amount I did not expect. I expected to withdraw 10USDC, but I'm actually withdrawing $10.03992 ? Why?

**Comment by TransmissionsDev** [comment]
It's to show the minimum amount you will receive because the token price can fluctuate.

**Comment by jameselkins-mantl** [comment]
This behavior is non-standard and bad UX. You should not close this ticket. You should either:
1. fix the behavior to not use a plain javascript alert and instead use a react.js component
2. display the minimum amount you receive as you input the number that you want to remove.
