### ISSUE TITLE
I should be able to withdraw the max amount of money in any particular token

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#141]
1. go to https://v2.rari.capital
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool
4. click on gear in upper-right hand corner of modal
5. click on 'want to withdraw'

Expected: See a button called "MAX" which prefills the input with the maximum amount of stable token I will receive
Actual: I am able to put any amount in here - even amounts which exceed my account balance

![image](https://user-images.githubusercontent.com/1206775/96829105-11547e80-1463-11eb-8f94-f3c3ee71f031.png)

**Comment by TransmissionsDev** [comment]
Moved to #150
