### ISSUE TITLE
Withdrawing from account balance requires excessive amounts of gas

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#142]
1. go to https://v2.rari.capital/
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool
4. click on gear in upper-right hand corner of modal
5. click on 'want to withdraw'
6. choose USDC
7. type "10" (assuming account balance is at least $10)
8. click "confirm"
9. click "ok" on the javascript alert

Expected: withdrawing takes max ~$5 of ETH
Actual: withdrawing takes ~$30 of ETH
![image](https://user-images.githubusercontent.com/1206775/96829296-8cb63000-1463-11eb-9870-641015729252.png)

**Comment by TransmissionsDev** [comment]
That's a reasonable amount. Moving funds out of multiple pools and swapping tokens causes this price.

**Comment by jameselkins-mantl** [comment]
This is not a reasonable amount. Withdrawing funds from other projects does not cost this amount of gas. I have moved funds in and out of luaswap, harvest.finance, and dracula.sucks . None of them were above $20.
