### ISSUE TITLE
it is unclear when the withdrawal fee is applied

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#143]
1. go to https://v2.rari.capital
2. Connect metamask wallet that has RPST
3. look at account balance

Outstanding question:
If my account balance is $100 and I withdraw, am I able to receive $100? ( & thus the $100 is already accounting for the .5% withdrawal fee ? ) Or am I only able to receive $99.5 ?

**Comment by TransmissionsDev** [comment]
$99.5.

**Comment by jameselkins-mantl** [comment]
You should not close this ticket as the issue has not been resolved. The issue is a UX issue that needs to be communicated in the website, not communicated to me specifically in this ticket.
