### ISSUE TITLE
it is hard to figure out how to withdraw money

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#144]
1. go to https://v2.rari.capital/
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool
4. click on gear in upper-right hand corner of modal

Expected:
I should see "withdraw" without having to click the gear

Actual:
I have to click the gear. This is very hidden.

Suggestion: instead of the gear, put a button saying "withdraw?" & then skip the screen of "withdraw" that happens when you click the gear as there is only 1 option
![image](https://user-images.githubusercontent.com/1206775/96829652-4a412300-1464-11eb-9c0d-597e8b8a611f.png)

skip this screen:
![image](https://user-images.githubusercontent.com/1206775/96829680-53ca8b00-1464-11eb-9028-3e22640d9dfe.png)
& go straight to this one:
![image](https://user-images.githubusercontent.com/1206775/96829703-5af19900-1464-11eb-962b-dd20c6d4f72c.png)

**Comment by keating** [comment]
It is better to have a withdraw button
