### ISSUE TITLE
change color of "confirm" button on withdraw modal from color of coin to red & color of "confirm" button on deposit modal from color of coin to green

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#145]
1. go to https://v2.rari.capital/
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool
4. click on gear in upper-right hand corner of modal
5. click 'want to withdraw?'
Expected: color of confirm button should be red
![image](https://user-images.githubusercontent.com/1206775/96829853-9ab88080-1464-11eb-986f-abdcae3e7cba.png)

Actual: color is blue above bc usdc is "blue"

1. go to https://v2.rari.capital/
2. Connect metamask wallet that has RPST
3. click on <> button under stable pool

Expected: color of confirm button should be green
![image](https://user-images.githubusercontent.com/1206775/96829923-b6238b80-1464-11eb-94d7-5dc42480e78c.png)

Actual: color is blue above bc usdc is "blue"

**Comment by TransmissionsDev** [comment]
Intentional, it matches the color of the token, not the validity of the deposit.

**Comment by jameselkins-mantl** [comment]
Yea but it's not good. The button color matching the token and/or changing color as you change tokens gives visual whiplash to the user and does not push them to take the action that you want and/or impart trust.
