### ISSUE TITLE
Max withdraw button

### ISSUE THREAD

**Issue by TransmissionsDev** [Rari-Capital/rari-dApp#150]

**Comment by TransmissionsDev** [comment]
Also need to use this to disable the confirm button for withdraws

**Comment by tongnk** [comment]
I can't see this in the UI? Was this deployed?

**Comment by TransmissionsDev** [comment]
@tongnk Correct not deployed waiting on @davidlucid who's overloaded with a lot of other things right now. It's our basically our top priority though :)

**Comment by TransmissionsDev** [comment]
Done!
