### ISSUE TITLE
UX Bug: finding commonly used tokens is hard

### ISSUE THREAD

**Issue by jameselkins** [Rari-Capital/rari-dApp#156]
1. go to https://v2.rari.capital/
2. Connect metamask wallet
3. click on <> button under stable pool
4. click the token that pops up (currently defaulted to DAI)
5. see list of tokens

Expected:
commonly used tokens should appear first (USDC, USDT, etc) (or at least after the tokens that you have in your wallet)

Actual:
tokens are organized alphabetically

**Comment by TransmissionsDev** [comment]
Doing #136 which is similar
