### ISSUE TITLE
Use toasts instead of alert for errors

### ISSUE THREAD

**Issue by TransmissionsDev** [Rari-Capital/rari-dApp#159]
See: https://chakra-ui.com/toast

**Comment by Yashs911** [comment]
Hi @TransmissionsDev I would like to work on this issue. Which file do I need to change.

**Comment by TransmissionsDev** [comment]
@Yashs911 Would love to have you give it a shot! Line `172` and `244` use `alert(e)`. Try replacing them with a call to the `toast` function in Chakra UI (https://chakra-ui.com/toast). You will need to add a call to `useToast()` to get the toast function above the `onDeposit` function. 
![ScreenShot-](https://user-images.githubusercontent.com/26209401/97034023-1b38b900-1519-11eb-9fe6-979a611c9387.png)
![ScreenShot-](https://user-images.githubusercontent.com/26209401/97034052-255ab780-1519-11eb-93aa-50b2bf7ee805.png)

Let me know if you have any further questions :)
