### ISSUE TITLE
[Documentation] Rari-api is a dead link

### ISSUE THREAD

**Issue by brettfazio** [Rari-Capital/rari-dApp#258]
'Rari API' links in https://github.com/Rari-Capital/rari-dApp/blob/master/src/rari-sdk/docs/pools/stable.md are dead

**Comment by TransmissionsDev** [comment]
Good point. @davidlucid needs to publish that repo 😅

**Comment by TransmissionsDev** [comment]
Pinged him on Slack. Will close when fixed :)
