### ISSUE TITLE
error loading app

### ISSUE THREAD

**Issue by dsummersja** [Rari-Capital/rari-dApp#259]
"TypeError: Cannot read property 'formattedBalance' of undefined"

**Comment by trybjm** [comment]
![error](https://user-images.githubusercontent.com/78935995/107703530-df1ba500-6d0f-11eb-9b26-73b501c7bd81.JPG)

**Comment by TransmissionsDev** [comment]
We were ratelimited by Infura. Fixed now. Thank you for the reports!
