### ISSUE TITLE
Not an issue with the app

### ISSUE THREAD

**Issue by chief10** [Rari-Capital/rari-dApp#262]
Hey there,

I don't have an issue with the app, I just don't know how else to get in touch with the creators. 

I was thinking of investing some money in RGT but after searching around the website and not finding anyones name attached to the project, I got kind of skeeved out and decided not to. My understanding of what the product does is that it holds other people's crypto to some degree. If that's the case, I would think you'd want people to feel comfortable enough to do that and that you won't simply run off with the crypto after enough adoption.

**Comment by TransmissionsDev** [comment]
Join our Discord and we can continue the conversation from there. 

https://discord.gg/mtb6W57Ap6
