### ISSUE TITLE
if a user has no supply/borrow, show tvl at the top instead

### ISSUE THREAD

**Issue by jbhav24** [Rari-Capital/rari-dApp#284]
or if the user isn't signed in to mm

**Comment by TransmissionsDev** [comment]
<img width="1029" alt="Screen Shot 2021-03-18 at 5 10 24 PM" src="https://user-images.githubusercontent.com/26209401/111713437-d8031d80-880c-11eb-9727-bbb22f3dc3a4.png">
Done
