### ISSUE TITLE
Unable to claim RGT rewards from pool2 page

### ISSUE THREAD

**Issue by jonathandiep** [Rari-Capital/rari-dApp#314]
To reproduce issue:
1. Stake SLP
2. Earn rewards (and do not claim them)
3. Unstake

Rewards are still claimable through the button in the header though

![Screen Shot 2021-03-19 at 7 39 27 PM](https://user-images.githubusercontent.com/8920301/111856939-706fcf80-88eb-11eb-9406-f78811014383.png)

**Comment by TransmissionsDev** [comment]
Ah good point. Resolving
