### ISSUE TITLE
Error connecting with wallet connect

### ISSUE THREAD

**Issue by tarrencev** [Rari-Capital/rari-dApp#337]
Ran into an error when trying to use wallet connect with Argent wallet:

![IMG_884688C09718-1](https://user-images.githubusercontent.com/4740651/112196405-63035f80-8be1-11eb-8a79-360df127333e.jpeg)

**Comment by TransmissionsDev** [comment]
I don't think this is an issue with our setup :(

**Comment by tarrencev** [comment]
ok will give it another shot and report back
