### ISSUE TITLE
ETH Pool incorrectly calculates "interest earned"

### ISSUE THREAD

**Issue by samajammin** [Rari-Capital/rari-dApp#367]
https://app.rari.capital/pools/eth

I'm seeing "ACCOUNT BALANCE" & "INTEREST EARNED" display the same value in the ETH pool (vs. [the stable pool](https://app.rari.capital/pools/stable), which looks to calculate interest correctly by subtracting the principal amount).

**Comment by rscdon** [comment]
I have this problem as well.

thx
