### ISSUE TITLE
If multiple deposits are added to a pool, interest rates seem to be calculated incorrectly.

### ISSUE THREAD

**Issue by josh-richardson** [Rari-Capital/rari-dApp#394]
If you deposit (for example) $10k into the stables pool, then accrue interest for a week, and subsequently deposit another $10k, the "Interest Earned" heading on the dashboard seems to think that your subsequent deposit into the pool qualifies as interest earned (i.e. the interest earned will display as over $10k, which definitely isn't correct). I did attempt to find the method that calculates this on the server side, but it unfortunately seems that `https://api.rari.capital/governance/` isn't available in the rari-capital org, so I can't submit a PR to attempt to fix.

**Comment by TransmissionsDev** [comment]
Yep we're aware of this. It's an issue with our internal API, will fix asap.

**Comment by josh-richardson** [comment]
Looks like this has been fixed.
