### ISSUE TITLE
Site broken on safari if content overflows

### ISSUE THREAD

**Issue by TransmissionsDev** [Rari-Capital/rari-dApp#398]
The new footer or something related in @sharad-s's recent changes seem to have broken the site on safari if the site overflows:

<img width="1043" alt="Screen Shot 2021-05-02 at 7 02 52 PM" src="https://user-images.githubusercontent.com/26209401/116835830-051b4d80-ab79-11eb-9c92-dc8310e4ddda.png">

**Comment by sharad-s** [comment]
Could you provide a bit more detail on how to replicate? Tested on Safari but seems fine (13" Macbook Air M1): 

<img width="947" alt="image" src="https://user-images.githubusercontent.com/8727763/116904359-d47bf800-abfa-11eb-9014-dcbb05c474f8.png">

**Comment by TransmissionsDev** [comment]
<img width="332" alt="Screen Shot 2021-05-03 at 11 03 00 AM" src="https://user-images.githubusercontent.com/26209401/116914075-2161cd80-abff-11eb-8ecf-d4c1c121dcef.png">
Able to reproduce on this version of Safari still.

**Comment by TransmissionsDev** [comment]
Was not able to reproduce on my iPad earlier but was able to reproduce with my iPhone.
