### ISSUE TITLE
Fuse Pool page overflowing window width on desktop sizes

### ISSUE THREAD

**Issue by sdn90** [Rari-Capital/rari-dApp#459]
<img width="1392" alt="Screen Shot 2021-10-14 at 7 51 05 PM" src="https://user-images.githubusercontent.com/2491713/137410630-dcfcbe4e-f276-4e59-863c-7629331a7ecb.png">

I did some investigating and it's due to a static width being set:

https://github.com/Rari-Capital/rari-dApp/blob/0df7d7a558546466b8842285b3d63ff22ebb3d68/src/components/pages/Fuse/FusePoolPage.tsx#L192

**Comment by transmissions11** [comment]
boutta push a fix
